import "bootstrap/dist/css/bootstrap.css";
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import HomePage from "../views-int/Home"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>SafeKeep</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </div>
  )
}

export default Home
